[project]
name = "duckdb-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "duckdb>=1.4.3",
    "harlequin>=2.5.1",
]
